speardevs_push_notifications_section:
    path: /{_locale}/account/push-notifications
    defaults:
        _controller: 'SpearDevs\SyliusPushNotificationsPlugin\Controller\Shop\PushNotificationAction'
        template: '@SpearDevsSyliusPushNotificationsPlugin/Shop/Account/push_notification.html.twig'

bentools_webpush:
    resource: '@WebPushBundle/Resources/config/routing.xml'
    prefix: /{_locale}/webpush
