sylius_resource:
    resources:
        app.user_subscription:
            classes:
                model: SpearDevs\SyliusPushNotificationsPlugin\Entity\UserSubscription
                repository: SpearDevs\SyliusPushNotificationsPlugin\Repository\MySQLUserSubscriptionRepository
        speardevs.push_notification_template:
            classes:
                model: SpearDevs\SyliusPushNotificationsPlugin\Entity\PushNotificationTemplate
