sylius_resource:
    resources:
        app.user_subscription:
            classes:
                model: SpearDevs\SyliusPushNotificationsPlugin\Entity\UserSubscription
                repository: SpearDevs\SyliusPushNotificationsPlugin\Repository\MySQLUserSubscriptionRepository
        sylius.shop_user:
            classes:
                model: Sylius\Component\Core\Model\ShopUser
                repository: SpearDevs\SyliusPushNotificationsPlugin\Repository\ShopUserRepository
        speardevs.push_notification_template:
            classes:
                model: SpearDevs\SyliusPushNotificationsPlugin\Entity\PushNotificationTemplate
