imports:
    - { resource: "../vendor/bentools/webpush-bundle/src/Resources/config/services.xml" }

services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    app.listener.shop.menu_builder:
        class: SpearDevs\SyliusPushNotificationsPlugin\Menu\Shop\AccountMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.shop.account, method: addAccountMenuItems }
    
    SpearDevs\SyliusPushNotificationsPlugin\Controller\PushNotificationAction:
        class: SpearDevs\SyliusPushNotificationsPlugin\Controller\PushNotificationAction
        arguments:
            - '@twig'
        tags:
            - { name: controller.service_arguments }
    
    SpearDevs\SyliusPushNotificationsPlugin\Services\UserSubscriptionManager :
        class: SpearDevs\SyliusPushNotificationsPlugin\Services\UserSubscriptionManager
        arguments:
            - '@doctrine'
        tags:
            - { name: bentools_webpush.subscription_manager, user_class: 'Sylius\Component\Core\Model\ShopUser' }
    
    SpearDevs\SyliusPushNotificationsPlugin\Command\WebPushNotificationCommand:
        class: SpearDevs\SyliusPushNotificationsPlugin\Command\WebPushNotificationCommand
        arguments:
            - '@sylius.repository.shop_user'
            - '@SpearDevs\SyliusPushNotificationsPlugin\Services\UserSubscriptionManager'
            - '@BenTools\WebPushBundle\Sender\PushMessageSender'
        tags:
            - { name: console.command }
