parameters:
    router.request_context.scheme: '%env(APP_SCHEME)%'
    images_directory: '/media/image'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $appScheme: '%router.request_context.scheme%'
            $imagesDirectory: '%images_directory%'
            Gaufrette\Filesystem: '@gaufrette.sylius_image_filesystem'
    
    SpearDevs\SyliusPushNotificationsPlugin\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Factory/'
            - '../src/Repository/'
            - '../src/Kernel.php'
            
    SpearDevs\SyliusPushNotificationsPlugin\Manager\UserSubscriptionManager:
        class: SpearDevs\SyliusPushNotificationsPlugin\Manager\UserSubscriptionManager
        arguments:
            - '@speardevs_sylius_push_notifications_plugin.repository.user_subscription'
            - '@sylius.repository.channel'
            - '@request_stack'
        tags:
            - { name: bentools_webpush.subscription_manager, user_class: 'SpearDevs\SyliusPushNotificationsPlugin\Entity\ShopUser' }
    
    SpearDevs\SyliusPushNotificationsPlugin\WebPushSender\WebPushSender:
        public: true
        
    app.listener.shop.menu_builder:
        class: SpearDevs\SyliusPushNotificationsPlugin\Menu\Shop\AccountMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.shop.account, method: addAccountMenuItems }

    app.listener.admin.menu_builder:
        class: SpearDevs\SyliusPushNotificationsPlugin\Menu\Admin\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    SpearDevs\SyliusPushNotificationsPlugin\Factory\PushNotificationHistoryFactory:
        decorates: speardevs_sylius_push_notifications_plugin.factory.push_notification_history
        arguments: [ '@.inner' ]
        
    SpearDevs\SyliusPushNotificationsPlugin\Form\Type\Admin\PushNotificationConfigurationType:
        arguments:
            - '%speardevs_sylius_push_notifications_plugin.model.push_notification_configuration.class%'
    
    SpearDevs\SyliusPushNotificationsPlugin\Context\ChannelContext:
        class: SpearDevs\SyliusPushNotificationsPlugin\Context\ChannelContext
        arguments:
            - '@sylius.repository.channel'
        tags:
            - { name: 'sylius.context.channel', priority: -256 }

sylius_user:
    resources:
        shop:
            user:
                classes:
                    model: SpearDevs\SyliusPushNotificationsPlugin\Entity\ShopUser
