winzou_state_machine:
    sylius_order:
        callbacks:
            after:
                sylius_send_web_push:
                    on: [ 'create' ]
                    do: [ '@SpearDevs\SyliusPushNotificationsPlugin\WebPush\WebPushSender', 'sendWebPush' ]
                    args: [ 'object', !php/const SpearDevs\SyliusPushNotificationsPlugin\WebPush\WebPushSender::PUSH_NEW_ORDER_CODE ]
                    priority: 100
