winzou_state_machine:
    sylius_shipment:
        callbacks:
            after:
                sylius_send_web_push:
                    on: [ 'ship' ]
                    do: [ '@SpearDevs\SyliusPushNotificationsPlugin\WebPush\WebPushSender', 'sendWebPush' ]
                    args: ['object.getOrder()', !php/const SpearDevs\SyliusPushNotificationsPlugin\WebPush\WebPushSender::PUSH_ORDER_SEND_CODE ]
                    priority: 100
