sylius_grid:
    grids:
        speardevs_push_notification_configuration:
            driver:
                options:
                    class: '%speardevs_sylius_push_notifications_plugin.model.push_notification_configuration.class%'
            fields:
                channel:
                    type: string
                    label: sylius.ui.channel
                iconPath:
                    type: twig
                    label: speardevs_sylius_push_notifications_plugin.ui.iconPath
                    options:
                        template: '@SpearDevsSyliusPushNotificationsPlugin/Admin/Grid/icon.html.twig'
            actions:
                item:
                    update:
                        type: update
